# ai_tasks.yaml
version: "1.1"  # 전체 YAML 파일 버전

# 사용 가능한 모델 목록
available_models:
  - name: "gpt-4"
    provider: "openai"
    description: "고급 추론 및 복잡한 작업을 위한 모델"
    max_tokens: 8192
  - name: "gpt-3.5-turbo"
    provider: "openai"
    description: "일반적인 텍스트 생성 및 대화를 위한 빠른 모델"
    max_tokens: 4096
  - name: "claude-3-opus"
    provider: "anthropic"
    description: "복잡한 작업과 자세한 분석을 위한 모델"
    max_tokens: 4096
  - name: "claude-3-haiku"
    provider: "anthropic"
    description: "빠른 응답과 간단한 작업을 위한 경량 모델"
    max_tokens: 2048
  - name: "gemini-pro"
    provider: "google"
    description: "다양한 텍스트 작업을 위한 범용 모델"
    max_tokens: 8192

tasks:
  # chat
  chat:
    system_prompt_template: 
    <<: *default_system_prompt_template

    

  # 기본 텍스트 완성 작업
  text_completion:
    name: "기본 텍스트 완성"
    description: "사용자 입력을 기반으로 자연스러운 텍스트를 생성합니다"
    version: "2.1"  # 작업 단위 버전
    created_at: "2024-05-01"
    updated_at: "2024-05-14"
    author: "AI 팀"
    model: "gpt-3.5-turbo"
    system_prompt_template: |
      당신은 텍스트를 자연스럽게 완성하는 전문가입니다. 사용자가 제공한 시작 텍스트를 기반으로 일관되고 논리적인 방식으로 내용을 확장하세요.
      {% if writing_style %}글쓰기 스타일: {{ writing_style }}{% endif %}
    system_input_variables:
      - writing_style
    system_partial_variables:
      system_context: "{{ system_context | default('일반') }}"
    user_prompt_template: |
      다음 텍스트를 자연스럽게 완성해주세요:
      {{ user_input }}
      {% if word_limit %}단어 수 제한: {{ word_limit }}단어{% endif %}
    user_input_variables:
      - user_input
    user_partial_variables:
      current_date: "{{ now() | date_format('%Y-%m-%d') }}"
      word_limit: "{{ word_limit | default('') }}"
    parameters:
      temperature: 0.7
      max_tokens: 150
      top_p: 0.9
    tags:
      - text_generation
      - completion
      - creative

  # 질문-답변 작업
  question_answering:
    name: "질문-답변"
    description: "주어진 질문에 명확하고 정확한 답변을 제공합니다"
    version: "1.5"
    created_at: "2024-04-15"
    updated_at: "2024-05-10"
    author: "지식 베이스 팀"
    model: "claude-3-haiku"
    system_prompt_template: |
      당신은 지식이 풍부한 도우미로, 사용자의 질문에 정확하고 간결하게 답변합니다. 
      {% if expertise %}전문 분야: {{ expertise }}{% endif %}
      {% if answer_style %}답변 스타일: {{ answer_style }}{% endif %}
    system_input_variables:
      - expertise
    system_partial_variables:
      answer_style: "{{ answer_style | default('간결하고 명확하게') }}"
    user_prompt_template: |
      {% if context %}
      다음 정보를 바탕으로 질문에 답변해주세요:
      
      컨텍스트:
      {{ context }}
      {% endif %}
      
      질문: {{ question }}
      {% if max_length %}답변 길이: {{ max_length }}{% endif %}
    user_input_variables:
      - question
      - context  # 선택적 변수
    user_partial_variables:
      max_length: "{{ max_length | default('') }}"
    parameters:
      temperature: 0.3
      max_tokens: 200
      top_p: 0.95
    tags:
      - qa
      - knowledge
      - information

  # 요약 작업
  summarization:
    name: "텍스트 요약"
    description: "긴 텍스트를 핵심 포인트만 포함하도록 요약합니다"
    version: "2.3"
    created_at: "2024-03-20"
    updated_at: "2024-05-12"
    author: "콘텐츠 팀"
    model: "gpt-4"
    system_prompt_template: |
      당신은 텍스트 요약 전문가입니다. 복잡하고 긴 텍스트를 이해하기 쉽게 요약하는 능력이 있습니다.
      {% if summarization_level %}요약 수준: {{ summarization_level }}{% endif %}
      {% if focus_area %}중점 영역: {{ focus_area }}{% endif %}
    system_input_variables:
      - focus_area
    system_partial_variables:
      summarization_level: "{{ summarization_level | default('표준') }}"
    user_prompt_template: |
      다음 텍스트를 요약해주세요:
      
      {{ content }}
      
      {% if style == "bullet_points" %}
      요점을 불릿 포인트로 요약하세요.
      {% elif style == "paragraph" %}
      요약을 단락 형태로 작성하세요.
      {% else %}
      주요 포인트 3-5개로 요약하세요.
      {% endif %}
      
      {% if target_length %}목표 길이: {{ target_length }}{% endif %}
    user_input_variables:
      - content
    user_partial_variables:
      style: "{{ style | default('default') }}"
      target_length: "{{ target_length | default('') }}"
    parameters:
      temperature: 0.4
      max_tokens: 250
      top_p: 0.85
    tags:
      - summarization
      - content_processing
      - text_analysis

  # 코드 생성 작업
  code_generation:
    name: "코드 생성"
    description: "설명을 기반으로 코드를 생성합니다"
    version: "3.0"
    created_at: "2024-02-10"
    updated_at: "2024-05-05"
    author: "개발 팀"
    model: "gpt-4"
    system_prompt_template: |
      당신은 숙련된 {{ programming_language }} 개발자입니다. 사용자의 요구사항에 맞는 효율적이고 가독성 높은 코드를 작성하세요.
      {% if code_style %}코딩 스타일: {{ code_style }}{% endif %}
      {% if complexity_level %}복잡성 수준: {{ complexity_level }}{% endif %}
      {% if include_tests == true %}단위 테스트를 포함하세요.{% endif %}
    system_input_variables:
      - programming_language
    system_partial_variables:
      code_style: "{{ code_style | default('표준') }}"
      complexity_level: "{{ complexity_level | default('중간') }}"
      include_tests: "{{ include_tests | default(false) }}"
    user_prompt_template: |
      다음 요구사항에 맞는 {{ language }} 코드를 생성해주세요:
      
      요구사항: {{ requirements }}
      
      {% if framework %}프레임워크: {{ framework }}{% endif %}
      {% if libraries %}사용할 라이브러리: {{ libraries }}{% endif %}
      {% if performance_considerations %}성능 고려사항: {{ performance_considerations }}{% endif %}
    user_input_variables:
      - requirements
      - language
    user_partial_variables:
      framework: "{{ framework | default('') }}"
      libraries: "{{ libraries | default('') }}"
      performance_considerations: "{{ performance_considerations | default('') }}"
    allowed_languages:
      - python
      - javascript
      - java
      - go
      - rust
      - typescript
      - c++
      - c#
    parameters:
      temperature: 0.2
      max_tokens: 500
      top_p: 0.95
    tags:
      - code
      - development
      - programming

  # 창의적 글쓰기 작업
  creative_writing:
    name: "창의적 글쓰기"
    description: "주어진 주제나 시작점을 기반으로 창의적인 내용을 작성합니다"
    version: "2.2"
    created_at: "2024-01-15"
    updated_at: "2024-04-28"
    author: "콘텐츠 팀"
    model: "claude-3-opus"
    system_prompt_template: |
      당신은 창의적인 작가입니다. {{ creative_format }} 형식으로 흥미롭고 매력적인 콘텐츠를 작성하세요.
      {% if genre %}장르: {{ genre }}{% endif %}
      {% if writing_technique %}글쓰기 기법: {{ writing_technique }}{% endif %}
      {% if author_style %}작가 스타일: {{ author_style }}{% endif %}
    system_input_variables:
      - creative_format
      - genre
    system_partial_variables:
      writing_technique: "{{ writing_technique | default('') }}"
      author_style: "{{ author_style | default('') }}"
    user_prompt_template: |
      다음 주제나 시작점을 기반으로 창의적인 {{ format }} 작품을 작성해주세요:
      
      {{ starting_point }}
      
      {% if tone %}톤: {{ tone }}{% endif %}
      {% if target_audience %}대상 독자: {{ target_audience }}{% endif %}
      {% if word_count %}단어 수: {{ word_count }}{% endif %}
    user_input_variables:
      - starting_point
      - format
    user_partial_variables:
      tone: "{{ tone | default('') }}"
      target_audience: "{{ target_audience | default('') }}"
      word_count: "{{ word_count | default('') }}"
    formats:
      - 짧은 이야기
      - 시
      - 대화
      - 에세이
      - 소설 구상
      - 희곡
      - 가사
    parameters:
      temperature: 0.9
      max_tokens: 800
      top_p: 1.0
    tags:
      - creative
      - writing
      - storytelling

  # 데이터 분석 작업
  data_analysis:
    name: "데이터 분석"
    description: "주어진 데이터를 분석하고 인사이트를 제공합니다"
    version: "1.8"
    created_at: "2024-03-05"
    updated_at: "2024-05-08"
    author: "데이터 과학 팀"
    model: "gemini-pro"
    system_prompt_template: |
      당신은 데이터 분석 전문가입니다. 주어진 데이터에서 중요한 패턴, 추세 및 인사이트를 식별하세요.
      {% if analysis_depth %}분석 깊이: {{ analysis_depth }}{% endif %}
      {% if statistical_methods %}사용할 통계적 방법: {{ statistical_methods }}{% endif %}
      {% if visualization_preferences %}시각화 선호도: {{ visualization_preferences }}{% endif %}
    system_input_variables:
      - analysis_depth
    system_partial_variables:
      statistical_methods: "{{ statistical_methods | default('기본') }}"
      visualization_preferences: "{{ visualization_preferences | default('') }}"
    user_prompt_template: |
      다음 데이터를 분석하고 주요 인사이트를 도출해주세요:
      
      {{ data }}
      
      {% if analysis_focus %}분석 중점: {{ analysis_focus }}{% endif %}
      {% if specific_questions %}구체적인 질문:
      {{ specific_questions }}{% endif %}
      {% if include_recommendations == true %}추천 사항을 포함하세요.{% endif %}
    user_input_variables:
      - data
    user_partial_variables:
      analysis_focus: "{{ analysis_focus | default('') }}"
      specific_questions: "{{ specific_questions | default('') }}"
      include_recommendations: "{{ include_recommendations | default(false) }}"
    parameters:
      temperature: 0.2
      max_tokens: 600
      top_p: 0.95
    tags:
      - data_analysis
      - insights
      - statistics

# 기본 설정
default_settings:
  language: "ko"
  response_format: "text"
  include_timestamps: false
  log_prompts: true
  user_feedback: true
  default_model: "gpt-3.5-turbo"  # 기본 모델 설정
  jinja_options:
    trim_blocks: true
    lstrip_blocks: true
    keep_trailing_newline: false
  version_control:
    track_usage: true
    store_history: true
    max_history_items: 10
    deprecation_warning: true  # 오래된 버전 사용 시 경고 표시
  default_prompt_setting:
    # 전역 시스템 메시지 설정 (특정 작업에 시스템 메시지가 정의되지 않은 경우 사용)
    default_system_prompt_template: &default_system_prompt_template | 
      당신은 유용하고 친절한 AI 어시스턴트입니다. 사용자의 요청에 정확하고 도움이 되는 응답을 제공하세요.
      항상 윤리적이고 안전한 방식으로 응답하며, 요청이 부적절한 경우 정중하게 거절하세요.
      {% if language %}응답은 {{ language }} 언어로 제공하세요.{% endif %}
    default_system_input_variables: &default_system_input_variables
      - language
    default_system_partial_variables: &default_system_partial_variables
      professionalism_level: "{{ professionalism_level | default('높음') }}"
    default_user_prompt_template: &default_system_prompt_template | 
      {{ content }}
    default_user_input_variables: &default_user_input_variables
      - content


# 샘플 작업 사용 예시
examples:
  - task: text_completion
    version: "2.1"
    model: "gpt-3.5-turbo"
    system_variables:
      writing_style: "논리적이고 설명적인"
    user_variables:
      user_input: "인공지능 기술은 현대 사회에서"
      word_limit: "100"
    expected_output: "인공지능 기술은 현대 사회에서 다양한 산업 분야에 혁신을 가져오고 있습니다. 의료, 금융, 교육, 제조업 등 거의 모든 분야에서 AI는 효율성을 높이고 새로운 가능성을 열고 있습니다..."
  
  - task: question_answering
    version: "1.5"
    model: "claude-3-haiku"
    system_variables:
      expertise: "인공지능 및 기계학습"
    user_variables:
      question: "인공지능과 머신러닝의 차이점은 무엇인가요?"
    expected_output: "인공지능(AI)은 인간의 지능을 모방하는 시스템을 광범위하게 지칭하는 용어입니다. 반면에 머신러닝(ML)은 AI의 하위 분야로, 데이터로부터 학습하여 성능을 개선하는 알고리즘을 다룹니다. 모든 머신러닝은 AI에 속하지만, 모든 AI가 머신러닝을 사용하는 것은 아닙니다."

# 모델 전환 설정
default_model_fallback: &default_model_fallback
  enable: true
  strategy: "cascade"  # cascade: 더 작은 모델로 단계적 하향, direct: 기본 모델로 바로 전환
  retry_attempts: 3
  fallback_sequence:
    - "gpt-4"
    - "claude-3-opus"
    - "gpt-3.5-turbo"
    - "claude-3-haiku"

# API 설정
api_config:
  openai:
    api_key_env: "OPENAI_API_KEY"
    organization_id_env: "OPENAI_ORG_ID"
    timeout: 30
  anthropic:
    api_key_env: "ANTHROPIC_API_KEY"
    timeout: 45
  google:
    api_key_env: "GOOGLE_API_KEY"
    timeout: 30
